name: 'Post releases to Discord'
env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASES_WEBHOOK }}
    
on:
  release:
    types:
    - published
 
jobs:
  post_on_discord:
    runs-on: ubuntu-latest
    
    steps:
    - uses: Ilshidur/action-discord@master
      with:
        args: "**Version {{ EVENT_PAYLOAD.release.tag_name }} has been released!**\n\nLink: {{ EVENT_PAYLOAD.release.html_url }}\n\n **Changelog:**\n{{ EVENT_PAYLOAD.release.body }}"
